export const UI_COPY = {
  language: 'Language',
  search: 'Search clients, people, actions…',
  openMenu: 'Open menu',
  collapse: 'Collapse',
  expand: 'Expand sidebar',
  signOut: 'Sign out',
  inviteOnly: 'Invite-only desk',
  unscheduled: 'Unscheduled',
  unscheduledHintDay: 'Drag onto an hour.',
  unscheduledHint: 'Drag onto a day or click the file.',
  viewAll: 'View all',
  missing: 'Missing',
  cannotCompute: 'Cannot compute',
  unverified: 'Unverified',
  titles: {
    board: 'Master Calendar Board',
    clients: 'Clients',
    profile: 'Client profile',
    questionnaire: 'Questionnaire',
    queue: 'Queue',
    engine: 'Engine',
    documents: 'Document lab',
    submissions: 'CYS / submissions',
    users: 'Users',
  },
  tiles: {
    finance_agreement: 'Finance agreement',
    signed_contract: 'Signed contract',
    utility_bill: 'Utility bill',
    comm_evidence: 'Comm evidence',
    ucc_lien: 'UCC Fixture / Lien',
    home_deed: 'Homeownership Deed',
    county_permit: 'County Permit Record',
    proposal: 'Proposal / savings estimate',
    lender_statement: 'Current lender statement',
    payoff_letter: 'Payoff quote',
    gov_id: 'Photo ID',
    other: 'Other documents',
    production_report: 'Solar Production Report',
  },
  nav: {
    board: 'Board',
    pipeline: 'Pipeline',
    clients: 'Clients',
    queue: 'Queue',
    documents: 'Document lab',
    submissions: 'CYS',
    desk: 'Desk',
    more: 'More',
  },
  week: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  today: 'Today',
  month: 'Month',
} as const

export type UiCopy = typeof UI_COPY
