import {afterEach,expect,it,vi} from 'vitest'
import {landingAfterLogin,staffRouteAllowed} from '@/lib/staff-routes'
afterEach(()=>vi.unstubAllEnvs())
it('keeps final interface within its visible surfaces and two roles',()=>{
 vi.stubEnv('PRODIGYFLO_FINAL_DESK','true')
 expect(staffRouteAllowed('SUPER_ADMIN','/engine')).toBe(true)
 expect(staffRouteAllowed('CLOSER','/engine')).toBe(false)
 expect(staffRouteAllowed('SUPER_ADMIN','/pipeline')).toBe(false)
 expect(staffRouteAllowed('SUPER_ADMIN','/settings/phone-numbers')).toBe(false)
 expect(staffRouteAllowed('CLOSER','/settings/users')).toBe(false)
 expect(staffRouteAllowed('CLOSER','/call-center')).toBe(true)
 expect(staffRouteAllowed('SUPER_ADMIN','/call-center')).toBe(true)
 expect(staffRouteAllowed('CLOSER','/clients/client-1/questionnaire')).toBe(true)
 expect(staffRouteAllowed('CLOSER','/clients/client-1/closeops')).toBe(false)
 expect(staffRouteAllowed('ADMIN','/board')).toBe(false)
 expect(staffRouteAllowed('CLOSER','/api/documents/doc-1/file')).toBe(true)
 expect(staffRouteAllowed('CLOSER','/api/voice/recordings/x')).toBe(true)
 expect(staffRouteAllowed('CLOSER','/api/voice/presence')).toBe(true)
})
it('final desk lets Super Admin open the Meta Ads page; closers stay out',()=>{
 vi.stubEnv('PRODIGYFLO_FINAL_DESK','true')
 expect(staffRouteAllowed('SUPER_ADMIN','/marketing/meta')).toBe(true)
 expect(staffRouteAllowed('SUPER_ADMIN','/marketing/meta/anything')).toBe(true)
 expect(staffRouteAllowed('SUPER_ADMIN','/marketing/metadata')).toBe(false)
 expect(staffRouteAllowed('SUPER_ADMIN','/marketing')).toBe(false)
 expect(staffRouteAllowed('CLOSER','/marketing/meta')).toBe(false)
 expect(staffRouteAllowed('ADMIN','/marketing/meta')).toBe(false)
})
it('turning off the flag restores the legacy admin route boundary',()=>{
 vi.stubEnv('PRODIGYFLO_FINAL_DESK','false')
 expect(staffRouteAllowed('SUPER_ADMIN','/settings/phone-numbers')).toBe(true)
 expect(staffRouteAllowed('SUPER_ADMIN','/engine')).toBe(false)
})
it('lets the installed app start page through so it can redirect to /board',()=>{
 vi.stubEnv('PRODIGYFLO_FINAL_DESK','true')
 expect(staffRouteAllowed('SUPER_ADMIN','/dashboard')).toBe(true)
 expect(staffRouteAllowed('CLOSER','/dashboard')).toBe(true)
})
it('drops a ?next= the role cannot open and lands on home instead',()=>{
 vi.stubEnv('PRODIGYFLO_FINAL_DESK','true')
 expect(landingAfterLogin('SUPER_ADMIN','/dashboard','/board')).toBe('/dashboard')
 expect(landingAfterLogin('SUPER_ADMIN','/call-center?lead=meta:o:1','/board')).toBe('/call-center?lead=meta:o:1')
 expect(landingAfterLogin('SUPER_ADMIN','/settings/phone-numbers','/board')).toBe('/board')
 expect(landingAfterLogin('CLOSER','/settings/users','/board')).toBe('/board')
 expect(landingAfterLogin('SUPER_ADMIN','/forbidden','/board')).toBe('/board')
 expect(landingAfterLogin('SUPER_ADMIN','//evil.example','/board')).toBe('/board')
 expect(landingAfterLogin('SUPER_ADMIN',null,'/board')).toBe('/board')
})
